<?php
require_once 'includes/database.php';
require_once 'includes/functions.php';

if (!isLoggedIn()) { header('Location: login.php'); exit; }
$stmt = $pdo->prepare("SELECT * FROM admin_users WHERE email = ?");
$stmt->execute([$_SESSION['user_email']]);
$admin = $stmt->fetch();
if (!$admin) { header('Location: dashboard.php'); exit; }
$admin_name = $admin['username'] ?? $_SESSION['user_name'];
$stmt = $pdo->query("SELECT COUNT(*) FROM applications WHERE status = 'pending'");
$pending_applications = $stmt->fetchColumn();
?>
<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>Settings - Admin</title><link rel="stylesheet" href="assets/css/admin-dashboard.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"></head><body>
<aside class="sidebar admin-sidebar"><div class="sidebar-header"><div class="logo-icon">🎓</div><h2 class="logo-text">Admin Panel</h2></div><nav class="sidebar-nav"><a href="admin-dashboard.php" class="nav-item"><i class="fas fa-chart-line"></i><span>Dashboard</span></a><a href="admin-users.php" class="nav-item"><i class="fas fa-users"></i><span>Users</span></a><a href="admin-courses.php" class="nav-item"><i class="fas fa-book"></i><span>Courses</span></a><a href="admin-applications.php" class="nav-item"><i class="fas fa-file-alt"></i><span>Applications</span><?php if($pending_applications>0): ?><span class="badge"><?php echo $pending_applications; ?></span><?php endif; ?></a><a href="admin-payments.php" class="nav-item"><i class="fas fa-credit-card"></i><span>Payments</span></a><a href="admin-documents.php" class="nav-item"><i class="fas fa-file"></i><span>Documents</span></a><a href="admin-notifications.php" class="nav-item"><i class="fas fa-bell"></i><span>Notifications</span></a><a href="admin-reports.php" class="nav-item"><i class="fas fa-chart-bar"></i><span>Reports</span></a><a href="admin-settings.php" class="nav-item active"><i class="fas fa-cog"></i><span>Settings</span></a></nav><div class="sidebar-footer"><a href="dashboard.php" class="nav-item"><i class="fas fa-home"></i><span>User View</span></a><a href="logout.php" class="nav-item logout"><i class="fas fa-sign-out-alt"></i><span>Logout</span></a></div></aside>
<main class="main-content"><header class="top-bar"><button class="mobile-toggle" id="mobileToggle"><i class="fas fa-bars"></i></button><div class="search-bar"><i class="fas fa-search"></i><input type="text" placeholder="Search..."></div><div class="top-bar-actions"><button class="icon-btn"><i class="fas fa-bell"></i></button><div class="user-menu"><img src="https://ui-avatars.com/api/?name=<?php echo urlencode($admin_name); ?>&background=4F46E5&color=fff" class="user-avatar"><span class="user-name"><?php echo htmlspecialchars($admin_name); ?></span><span class="user-role">Admin</span></div></div></header>
<section class="welcome-section"><div class="welcome-content"><h1><i class="fas fa-cog"></i> System Settings</h1><p>Configure your platform settings.</p></div></section>
<section class="quick-actions"><h2>Settings Categories</h2><div class="actions-grid"><a href="#" class="action-card"><i class="fas fa-globe"></i><span>General Settings</span></a><a href="#" class="action-card"><i class="fas fa-envelope"></i><span>Email Settings</span></a><a href="#" class="action-card"><i class="fas fa-shield-alt"></i><span>Security</span></a><a href="#" class="action-card"><i class="fas fa-palette"></i><span>Appearance</span></a><a href="#" class="action-card"><i class="fas fa-database"></i><span>Backup</span></a><a href="#" class="action-card"><i class="fas fa-plug"></i><span>Integrations</span></a></div></section>
<div class="dashboard-grid"><section class="card"><div class="card-header"><h2><i class="fas fa-info-circle"></i> System Information</h2></div><div class="card-content"><p style="margin-bottom:1rem;"><strong>Version:</strong> 1.0.0</p><p style="margin-bottom:1rem;"><strong>PHP Version:</strong> <?php echo phpversion(); ?></p><p style="margin-bottom:1rem;"><strong>Database:</strong> MySQL</p><p style="margin-bottom:1rem;"><strong>Server:</strong> <?php echo $_SERVER['SERVER_SOFTWARE']; ?></p></div></section><section class="card"><div class="card-header"><h2><i class="fas fa-tools"></i> Quick Actions</h2></div><div class="card-content"><button class="btn btn-secondary" style="width:100%;margin-bottom:1rem;" onclick="alert('Clear cache feature coming soon!')"><i class="fas fa-broom"></i> Clear Cache</button><button class="btn btn-secondary" style="width:100%;margin-bottom:1rem;" onclick="alert('Backup feature coming soon!')"><i class="fas fa-download"></i> Backup Database</button><button class="btn btn-secondary" style="width:100%;" onclick="alert('Maintenance mode coming soon!')"><i class="fas fa-wrench"></i> Maintenance Mode</button></div></section></div></main>
<script src="/assets/js/dashboard.js"></script>
</body></html>